-- MySQL Script generated by MySQL Workbench
-- Wed Mar 21 13:24:57 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Pacjenci`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pacjenci` (
  `PESEL` VARCHAR(11) NOT NULL,
  `imie` VARCHAR(45) NOT NULL,
  `nazwisko` VARCHAR(45) NOT NULL,
  `wiek` INT NOT NULL,
  `nr_telefonu` VARCHAR(12) NULL DEFAULT NULL,
  PRIMARY KEY (`PESEL`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Zabiegi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Zabiegi` (
  `idZabiegu` INT NOT NULL AUTO_INCREMENT,
  `nazwa_zabiegu` VARCHAR(80) NOT NULL,
  `cena` INT NOT NULL DEFAULT 0,
  `narkoza` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`idZabiegu`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Dentysci`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Dentysci` (
  `idDentysty` INT NOT NULL AUTO_INCREMENT,
  `imie` VARCHAR(45) NOT NULL,
  `nazwisko` VARCHAR(45) NOT NULL,
  `wynagrodzenie` INT NOT NULL DEFAULT 0,
  `data zatrudnienia` DATE NULL DEFAULT NULL,
  `nr_telefonu` VARCHAR(12) NULL DEFAULT NULL,
  PRIMARY KEY (`idDentysty`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Rejestracje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Rejestracje` (
  `idRejestracji` INT NOT NULL AUTO_INCREMENT,
  `godzina` TIME(6) NOT NULL,
  `data` DATE NOT NULL,
  `pacjent` VARCHAR(11) NOT NULL,
  `dentysta` INT NOT NULL,
  PRIMARY KEY (`idRejestracji`, `pacjent`, `dentysta`),
  INDEX `pacjent_idx` (`pacjent` ASC),
  UNIQUE INDEX `godzina_UNIQUE` (`godzina` ASC),
  INDEX `dentysta_idx` (`dentysta` ASC),
  CONSTRAINT `pacjent`
    FOREIGN KEY (`pacjent`)
    REFERENCES `mydb`.`Pacjenci` (`PESEL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `dentysta`
    FOREIGN KEY (`dentysta`)
    REFERENCES `mydb`.`Dentysci` (`idDentysty`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Bonifikarta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Bonifikarta` (
  `idbonifikarta` INT NOT NULL AUTO_INCREMENT,
  `typ` INT NULL DEFAULT 0,
  `mozliwy_rabat` INT NOT NULL DEFAULT 0,
  `data_waznosci` DATE NULL DEFAULT NULL,
  `idPacjenta` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`idbonifikarta`),
  INDEX `pacjent_idx` (`idPacjenta` ASC),
  CONSTRAINT `idPacjenta`
    FOREIGN KEY (`idPacjenta`)
    REFERENCES `mydb`.`Pacjenci` (`PESEL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Zabiegi_na_rejestracje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Zabiegi_na_rejestracje` (
  `Zabiegi_idZabiegu` INT NOT NULL,
  `Rejestracje_idRejestracji` INT NOT NULL,
  PRIMARY KEY (`Zabiegi_idZabiegu`, `Rejestracje_idRejestracji`),
  INDEX `fk_Zabiegi_has_Rejestracje_Rejestracje1_idx` (`Rejestracje_idRejestracji` ASC),
  INDEX `fk_Zabiegi_has_Rejestracje_Zabiegi1_idx` (`Zabiegi_idZabiegu` ASC),
  CONSTRAINT `fk_Zabiegi_has_Rejestracje_Zabiegi1`
    FOREIGN KEY (`Zabiegi_idZabiegu`)
    REFERENCES `mydb`.`Zabiegi` (`idZabiegu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Zabiegi_has_Rejestracje_Rejestracje1`
    FOREIGN KEY (`Rejestracje_idRejestracji`)
    REFERENCES `mydb`.`Rejestracje` (`idRejestracji`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
